Support Python 3.7
spoqa/settei pull request #28
Opened 2018-08-13 08:40 UTC by dahlia

2018-08-13 09:03 UTC, admire93 commented
The test was failed.

2018-08-14 01:51 UTC, admire93 commented
@dahlia The reason why the test was failed is Travis-CI dosen't support Python 3.7 yet. Consider bypassing it like I did in [this file](https://github.com/admire93/pyleftpad/blob/master/.travis.yml#L7-L12).

2018-08-16 10:17 UTC, dahlia commented
@admire93 @hanc1208 Fixed the Python 3.7 build which was failed.  Python 3.4 build is still failing due to the changelog check and IMHO it's okay to ignore.

2018-08-17 01:33 UTC, hanc1208 requested changes

2018-08-17 01:33 UTC, hanc1208 commented on settei/base.py
> +    # For newer versioss of typing (>= Python 3.7)
typo `versioss` -> `versions`

2018-08-17 03:28 UTC, admire93 commented
I think we can mere this PR after fixing one problem @hanc1208 mentioned.

2018-08-21 07:11 UTC, dahlia commented on settei/base.py
> +    # For newer versioss of typing (>= Python 3.7)
Fixed: cc47a82b46848d858fe6620b5371fc7415f96f35

2018-08-21 07:17 UTC, kanghyojun approved these changes

2018-08-21 07:54 UTC, hanc1208 approved these changes

2018-08-21 07:55 UTC, merged