Reopen #27 Cache config value when `cached` is `True`
spoqa/settei pull request #32
Opened 2019-10-01 08:37 UTC by wisemuji

https://github.com/spoqa/settei/pull/27
Checked some reviews, merged conflicts.

2019-10-02 03:20 UTC, hanc1208 commented on tests/base_test.py
> +    assert cached_id == id(tc.cached)
`config_object_property`도 테스트해주세요.

2019-10-02 03:21 UTC, hanc1208 commented on tests/base_test.py
> +    assert cached_id == id(tc.cached)
이거 항상 같을 수 밖에 없지 않나요?

2019-10-02 03:25 UTC, hanc1208 commented on settei/base.py
> +                if obj is None:
`self.raw_value`랑 동작이 겹치는 것 같아요.

2019-10-02 03:27 UTC, hanc1208 commented on settei/base.py
> +            instance = getattr(obj, cache_key, None)
`None`이 아니라 `KeyError`를 catch 해야할 것 같아요. (https://github.com/spoqa/settei/pull/27/files#r208453918)

2019-10-07 05:10 UTC, hanc1208 commented on settei/base.py
> +            cache_key = '  cache_{!s}'.format(self.key)
문자열에 공백은 몬가요

2019-10-07 05:12 UTC, hanc1208 commented on tests/base_test.py
> +    tc = TestConfig({'cached': True})
`cached`가 `bool`이라 언제나 id가 같을 것 같아요.

2019-10-07 08:50 UTC, wisemuji commented on tests/base_test.py
> +    tc = TestConfig({'cached': True})
그럼 이와 같은 경우에는 어떤 방식으로 테스트를 진행하면 좋을까요?

2019-10-08 06:26 UTC, hanc1208 commented on settei/base.py
> +            cache_key = 'cache_{!s}'.format(self.key)
공백이 의도적이었을 것 같긴한데요..!!!!!!

2019-10-08 06:26 UTC, hanc1208 commented on tests/base_test.py
> +    assert ex.value.args[
같은 줄로 합치는게 낫지않을까요?

2019-10-08 06:27 UTC, hanc1208 commented on tests/base_test.py
> +    tc = TestConfig(cached=True)
`TestConfig.cached`의 타입이 `bool`인 이상 테스트가 의미가 없을 것 같아요. `bool`은 값이 같으면 주소가 같습니다.

2019-10-08 06:32 UTC, wisemuji commented on tests/base_test.py
> +    assert ex.value.args[
합칠 경우 글자 수가 80자를 넘게 됩니다.

2019-10-08 06:36 UTC, wisemuji commented on settei/base.py
> +            cache_key = 'cache_{!s}'.format(self.key)
공백이 있어도 Attribute name으로 허용되므로 다시 추가하겠습니당...!

2019-10-08 06:37 UTC, wisemuji commented on settei/base.py
> +            cache_key = 'cache_{!s}'.format(self.key)
공백을 포함시키면 getattr으로만 불러올 수 있는 것 같아요

2019-10-08 06:37 UTC, hanc1208 commented on tests/base_test.py
> +    assert ex.value.args[
# noqa 를 붙이면 80자 넘어도 확인하지 않습니다. (flake8 우회)
한 줄에 있는게 더 보기 좋을 것 같아요.

2019-10-08 06:38 UTC, wisemuji commented on tests/base_test.py
> +    tc = TestConfig(cached=True)
그럼 `assert tc.cached is True` 구문만 제거하면 되나요?

2019-10-08 06:38 UTC, hanc1208 commented on settei/base.py
> +            cache_key = 'cache_{!s}'.format(self.key)
네 이 attriubte를 외부에서 쓰면 안되니까 공백 넣는게 좋을 것 같아요.

2019-10-08 06:44 UTC, hanc1208 commented on tests/base_test.py
> +    tc = TestConfig(cached=True)
테스트 코드가 문제가 아니라 `TestConfig.cached`가 문제 입니다.
`bool`,`int`,`float` 이런 primitive 타입이 아니여야할 것 같아요.

2019-10-08 09:41 UTC, wisemuji commented on tests/base_test.py
> +    tc = TestConfig(cached=True)
나머지 테스트는 어떻게 하면 좋을까용...

2019-10-10 01:18 UTC, hanc1208 commented on tests/base_test.py
> +    tc = TestConfig(cached='true')
아쉽게도 문자열도 캐싱이 됩니다.

2019-10-10 01:18 UTC, hanc1208 commented on tests/base_test.py
> +    tc = TestConfig(cached='true')
```
Python 2.7.16 (default, Mar  4 2019, 09:01:38)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> id('true')
4483618304
>>> id('true')
4483618304
```

2019-10-11 06:52 UTC, pbzweihander requested changes

2019-10-11 06:52 UTC, pbzweihander commented on docs/changes.rst
> +Version 0.5.5
0.5.5 를 추가하지 말고, 0.5.4를 To be released로 놓고 그 밑에 변경사항을 달고, 0.5.4가 release 될 때 0.5.5를 추가해주는 것입니다. https://github.com/spoqa/settei/pull/30/files 를 참고하시면 좋습니다.

2019-10-17 09:09 UTC, wisemuji commented on docs/changes.rst
> +Version 0.5.5
네! 참고하겠습니다.

2019-10-23 04:40 UTC, pbzweihander requested changes

2019-10-23 04:40 UTC, pbzweihander commented on docs/changes.rst
> +
여기 newline은 왜 추가된 것인가요?

2019-10-23 04:40 UTC, pbzweihander commented on settei/base.py
> -
여기 newline은 왜 없어진 것인가요..?

2019-10-23 04:40 UTC, pbzweihander commented on settei/base.py
> +                hasattr(type_, '__args__'):
여기는 꼭 바뀔 필요가 있었나요?

2019-10-23 04:40 UTC, pbzweihander commented on settei/base.py
> +                 *, cached: bool = False,
kwargs를 받는다면 cached라는 keyword argument를 추가하기보다 kwargs 안에서 찾는게 일관성 있을 것 같아요

2019-10-23 04:40 UTC, pbzweihander commented on settei/base.py
> +                not isinstance(args, collections.abc.Sequence):
여기도 꼭 바뀔 필요가 있었나요?

2019-10-23 04:40 UTC, pbzweihander commented on settei/base.py
> +            cache_key = '  cache_{!s}'.format(self.key)
default 부분을 처리하는 부분을 `default_check` 라고 뺐으니 cache를 처리하는 부분도 `cache_check` 같은 이름으로 빼는 건 어떻게 생각하시나요?

2019-10-23 04:53 UTC, wisemuji commented on settei/base.py
> +                hasattr(type_, '__args__'):
그 부분은 @kanghyojun 님이 변경하신 걸로 알고 있습니다.

2019-10-23 04:53 UTC, wisemuji commented on settei/base.py
> +                 *, cached: bool = False,
네 좋아용!!

2019-10-23 04:53 UTC, wisemuji commented on settei/base.py
> +                not isinstance(args, collections.abc.Sequence):
그 부분도 @kanghyojun 님이 변경하신 걸로 알고 있습니다.

2019-10-23 04:54 UTC, wisemuji commented on settei/base.py
> +            cache_key = '  cache_{!s}'.format(self.key)
네네 그 편이 좋겠네요!!

2019-10-23 04:56 UTC, kanghyojun commented on settei/base.py
> +                hasattr(type_, '__args__'):
린터가 잡은것아닐까요?

2019-10-23 04:57 UTC, wisemuji commented on settei/base.py
> -
원래 `__all__ = ...`과 `if hassattr(...`사이에는 newline이 하나만 추가되는 것이 맞지 않나용...?

2019-10-23 04:57 UTC, kanghyojun commented on settei/base.py
> +                 *, cached: bool = False,
그럼 kwargs를 안받게하시는게 더 나을 것 같은게요. `cached`라는게 명시적으로 들어가는게 IDE 힌팅에 도움이 됩니다.

2019-10-23 04:57 UTC, kanghyojun reviewed
코멘트 남겻어오

2019-10-23 05:04 UTC, kanghyojun commented on settei/base.py
> -
가장 밖에 레벨에서는 2줄이니까 두줄이 맞는거같아여

2019-10-23 05:05 UTC, wisemuji commented on settei/base.py
> -
넹 알겠습니당~!~!

2019-10-23 05:06 UTC, pbzweihander commented on settei/base.py
> +                 *, cached: bool = False,
네 밑에 잇는 `default_func` 같은 것도 다 keyword arg로 바꾸면 좋을 거 같네요

2019-10-23 05:09 UTC, wisemuji commented on settei/base.py
> +                 *, cached: bool = False,
알겠숩니당

2019-10-23 07:31 UTC, wisemuji commented on settei/base.py
> +                 *, cached: bool = False,
생각해보니 `default` 같은 경우 기존에는 kwargs로 받았고 밑에 코드에서 `elif 'default' in kwargs:`로 사용자가 파라미터를 넘겼는지 여부를 확인하는데, kwargs를 없애고 파라미터로 받으면 사용자가 호출했는지 여부를 어떻게 검사하나요? `def __init__(..., default=None)`로 하고 `elif default is not None:`로 검사하는 경우 사용자가 `default=None`로 파라미터를 넘기는 경우를 감지할 수 없습니다.

2019-10-23 07:34 UTC, pbzweihander commented on settei/base.py
> +                 *, cached: bool = False,
아.... `default=None` 을 쓰면 못잡는군요 그걸 생각 못했네요....... 그럼 keyword arg로 뺄 수 있는건 빼되 이런 경우만 kwargs를 쓰면 될 거 같네요

2019-10-23 07:35 UTC, wisemuji commented on settei/base.py
> +                 *, cached: bool = False,
네넨 좋습니다!!

2019-10-23 07:43 UTC, wisemuji commented on settei/base.py
> +                hasattr(type_, '__args__'):
일단은 지울게요!!

2019-10-23 07:49 UTC, pbzweihander commented on settei/base.py
> +            return self.default_check(default, expression, obj)
`cache_check` 안에서 `default_check`를 호출하는게 조금 부자연스럽다는게 아쉽네요..

2019-10-23 07:50 UTC, pbzweihander approved these changes

2019-10-23 07:50 UTC, Jhuni0123 commented on tests/base_test.py
> +    tc = TestConfig(cached='true')
그냥 지나가다 보여서 남깁니다,,
```python
>>> id('true') == id('true')
True
```
이렇게 안하면 'true'를 할당했다 해제할 수 있어서 캐시되는지 여부를 알 수 없습니다

ex)
```python
>>> id('aa')
4328350192
>>> id('ab')
4328350192
```

2019-10-23 07:51 UTC, wisemuji commented on settei/base.py
> +            return self.default_check(default, expression, obj)
흑 그러게여.......

2019-10-23 07:53 UTC, wisemuji commented on tests/base_test.py
> +    tc = TestConfig(cached='true')
헉 이건 정말 몰랐어요...!!!! 알려주셔서 감사합니다!!

2019-10-23 07:58 UTC, hanc1208 commented on tests/base_test.py
> +    tc = TestConfig(cached='true')
ㅎㄸ

2019-10-24 02:32 UTC, hanc1208 commented on tests/base_test.py
> +    cached = config_property('cached', Enum1, cached=True)
필요 없는 것 같아요.

2019-10-24 04:22 UTC, wisemuji commented on tests/base_test.py
> +    cached = config_property('cached', Enum1, cached=True)
앗 그러네용ㅋㅋㅋㅋㅋㅋ

2019-10-29 01:29 UTC, hanc1208 approved these changes

2019-10-29 01:33 UTC, merged