Change to can set web and worker config as environment value
spoqa/settei pull request #40
Opened 2020-06-17 06:54 UTC by kimdoori

- Change to can set web and worker config as environment value
- Set to worker_result_backend default None
- Update refer docs link

2020-06-17 07:44 UTC, AiOO requested changes
Very thanks for your contribution.

Because there are `on_loaded` configs on both `WebConfiguration` and `WorkerConfiguration` already, I think the main problem of this issue is not to fill `config` values when importing settings from environment variables. So how about to fix about that problem?

https://github.com/spoqa/settei/blob/cd19c7c1f896a708dcf14311b0fbc746a9684b00/settei/presets/flask.py#L119

https://github.com/spoqa/settei/blob/cd19c7c1f896a708dcf14311b0fbc746a9684b00/settei/presets/celery.py#L240

On the other hand, added options and updated references are good. :+1:

2020-06-17 07:44 UTC, AiOO commented on settei/presets/celery.py
> +        https://docs.celeryproject.org/en/master/userguide/configuration.html#std:setting-broker_url
I think this link is better.
```suggestion
        https://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-broker_url
```

2020-06-17 07:44 UTC, AiOO commented on settei/presets/celery.py
> +        https://docs.celeryproject.org/en/master/userguide/configuration.html#std:setting-result_backend
I think this link is better. (2)
```suggestion
        https://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-result_backend
```

2020-06-17 07:44 UTC, AiOO commented on settei/presets/celery.py
> +        https://docs.celeryproject.org/en/master/userguide/configuration.html#std:setting-imports
I think this link is better. (3)
```suggestion
        https://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-imports
```

2020-06-17 07:44 UTC, AiOO commented on settei/presets/celery.py
> +            ON_LOADED=self.worker_on_loaded,
I think `celery_config['ON_LOADED']` is not used.

2020-06-17 07:44 UTC, AiOO commented on settei/presets/flask.py
> +            ON_LOADED=self.web_on_loaded,
I think `web_config['ON_LOADED']` is not used.

2020-06-17 08:12 UTC, kimdoori commented
I don't have time to change the code right now, so I'll request a review later.

2020-06-17 08:31 UTC, kanghyojun requested changes

2020-06-17 08:31 UTC, kanghyojun commented on settei/presets/flask.py
> +        on_loaded = self.config.get('web', {}).get('on_loaded', []) or self.web_on_loaded
이게 지금보니까 `self.web_config.get('on_loaded', [])`가 되어야할거같은느낌이네요.

2020-06-17 08:31 UTC, kanghyojun commented on tests/presets/celery_test.py
> +from ..base_test import os_environ
test에선 import해서 쓰지 말고 fixture로 만들어서씁시다!

2020-06-17 08:31 UTC, kanghyojun commented on settei/presets/flask.py
> +            ON_LOADED=self.web_on_loaded,
```suggestion
            ON_LOADED=self.web_on_loaded,
```
이게 안쓰이기도 할텐데, `web_config.update(ON_LOADED=self.web_on_loaded)`로 한줄로 써도되지않나요?

2020-06-17 08:31 UTC, kanghyojun commented on settei/presets/flask.py
> +        default=[]
기본적으로는 없을 수 있음을 가정하니까 `None`이  기본값이 되면 좋을것 같아요.

2020-06-17 08:31 UTC, kanghyojun commented on settei/presets/flask.py
> +            web_config = {k.upper(): v for k, v in raw_config.items()}
`raw_config가 이미 `collections.abc.Mapping`이니까 `raw_config`에 직접 `self.web_on_loaded`를 업데이트하고 맨마지막에 return 하기전에 키를 대문자로 만드는 로직으로 만들면 좋을거같아요

2020-06-17 08:31 UTC, kanghyojun commented on settei/presets/flask.py
> +        return web_config
`web_config`는 readonly value여야해서 `ImmutableDict`인게 좋은거같아요.

2020-06-17 08:31 UTC, kanghyojun commented on settei/presets/flask.py
> +            ON_LOADED=self.web_on_loaded,
`self.web_on_loaded`가 있을때만(`None`이나 `[]`이 아닐때만) 업데이트 해야하지않을까요?

2020-06-17 08:35 UTC, kimdoori commented
@kanghyojun 아앗 리뷰 감사합니다!! 브라이트님과 구두로 이 작업 방향보다는 애초에 config를 환경 변수로 넣어줄 수 있도록 작업 하는 것이 나을 것 같다고 논의했습니다. 다시 작업해서 리뷰 요청드릴게요! cc @AiOO

2020-06-17 08:51 UTC, pbzweihander commented
제 생각에는 Configuration class (https://github.com/spoqa/settei/blob/master/settei/base.py#L715) 의 구현을 그냥 Mapping이 아니고 뭔가 EnvAwareMapping 같은 걸로 바꿔서, `__getitem__` 할 때 마다 env를 먼저 긁어보도록 하면 좋을 거 같아요.

문제는 EnvAwareMapping이 돌려주는 값이 Mapping이면 이 친구도 EnvAwareMapping으로 감싸서 돌려줄 수 있도록 해야해요. 
또한 이렇게 recursive하게 감싸서 돌려주는 EnvAwareMapping이 자기 자신의 parent의 key를 계속 들고 있어야해요.
그래야 `foo.bar.baz` 같은 키도 `FOO__BAR__BAZ` 로 잘 참조할 수 있을테니까요.

2020-07-01 07:34 UTC, kimdoori commented on tests/presets/celery_test.py
> +from ..base_test import os_environ
utils 파일로 분리했습니다!

2020-07-02 01:21 UTC, kanghyojun commented on settei/base.py
> +class EnvConfigurationReader:
`EnvConfigurationReader`가 `dict`나 `collections.abc.Mapping`같은것을 상속받아서 구현하는것을 생각하긴했어요. `config_property.config`자체가 `EnvConfigurationReader` 타입이어야할거같고 `EnvConfigurationReader`안에서 `dict`를 lookup하면 `EnvConfigurationReader`를 다시 반환하는 형태가 되면 좋을 거 같아요. 다만 변경점이 좀 많을 것 같아서 이건 가이 페어 프로그래밍 하면 좋을거같아요

2020-07-02 01:21 UTC, kanghyojun commented on settei/base.py
> +    """Read the configuration from the environment variables.
`Read the environment variables to make `dict`` 정도의 설명이 이 클래스에 어울리지 않을까요.

2020-07-02 01:21 UTC, kanghyojun commented on settei/base.py
> +class config_property(EnvConfigurationReader):
위에서 언급했지만 `dict`를 받아서 `EnvConfigurationReader`가 만들어진다면 `config_property`는 `EnvConfigurationReader`를 상속 받지 못하게됩니다.

2020-07-13 09:01 UTC, kimdoori commented
@kanghyojun 저번에 같이 페어했던 부분 + `ASTERISK`와 `SETTEIENVLIST`도 동작하도록 보완해서 올렸습니다.

on_loaded 함수에서 worker_config 나 web_config를 사용하도록 하고 싶은데 혹시 좋은 방법을 아시나요?

2020-07-16 06:01 UTC, kanghyojun requested changes

2020-07-16 06:01 UTC, kanghyojun commented on settei/parse_env.py
> +class EnvReader(typing.Mapping):
`collections.abc.Mapping`을 상속받아야할거같아요. `typing.Mapping`은 타입 애너테이션용으로 만들어진 친구니까요!

2020-07-16 06:01 UTC, kanghyojun commented on settei/parse_env.py
> +                os_key = self.DELIMITER.join([self.froms] + [upper_key])
`froms`가 리스트가 아니라면 

```suggestion
                os_key = self.DELIMITER.join([self.froms, upper_key])
```

정도로 고칠 수 있을 거같네요

2020-07-16 06:01 UTC, kanghyojun commented on settei/parse_env.py
> +                os_key = self.DELIMITER.join([self.froms] + [upper_key])
위에 type annotation에서는 리스트여서 혹시 이거 `[[], item]`이런걸 의도한건가요?

2020-07-16 06:01 UTC, kanghyojun commented on settei/parse_env.py
> +        if not any([asterisk_indexes, list_indexes]):
2개 아이템 정도는 `if not (asterisk_indexes or list_indexes)`정도가 더 좋은거같기도 하네요. 아무래도 `list`를 만드는 비용과 `any`가 리스트를 순회하는 비용도 있을테니까요

2020-07-16 06:01 UTC, kanghyojun commented on tests/parse_env_test.py
> +        assert d['a']['c'] == '2'
혹시 `A__C`와 `A`가 둘다 있을때 `d['a']`와 `d['a']['c']` 전부 잘 출력되는 테스트 추가해주실수 있을까요?

2020-07-16 06:01 UTC, kanghyojun commented on tests/parse_env_test.py
> +        assert d['a']['b'] == 'test'
`SETTEIENVLIST`랑 그냥 os environ이랑 둘다 있으면 한쪽이 우선된다는 테스트인거죠? 주석달아두면 좋을거같아요

2020-07-16 06:02 UTC, kanghyojun commented
> on_loaded 함수에서 worker_config 나 web_config를 사용하도록 하고 싶은데 혹시 좋은 방법을 아시나요?

@kimdoori 혹시 이거 조금 더 자세하게 설명 들을 수 있을까요?

2020-07-23 05:32 UTC, kimdoori commented on settei/parse_env.py
> +                os_key = self.DELIMITER.join([self.froms] + [upper_key])
앗... 무슨 생각이었는지는 기억이 잘 안나지만 str이 맞는 것 같습니다!

2020-07-23 05:32 UTC, kimdoori commented on settei/parse_env.py
> +        if not any([asterisk_indexes, list_indexes]):
그렇군요! 감사합니다 🙇

2020-07-23 05:32 UTC, kimdoori commented on settei/parse_env.py
> +class EnvReader(typing.Mapping):
네넵 감사합니다

2020-07-23 05:49 UTC, kimdoori commented on tests/parse_env_test.py
> +        assert d['a']['c'] == '2'
@kanghyojun 둘 다 잘 출력되어야하나요? A__C, A 둘 다 있다면 d['a'] 만 출력되어야하는 거 아닌가요?!

2020-07-23 05:53 UTC, kimdoori commented on tests/parse_env_test.py
> +        assert d['a']['b'] == 'test'
넵넵!

2020-07-23 05:57 UTC, kimdoori commented
> > on_loaded 함수에서 worker_config 나 web_config를 사용하도록 하고 싶은데 혹시 좋은 방법을 아시나요?
> 
> @kimdoori 혹시 이거 조금 더 자세하게 설명 들을 수 있을까요? 왠지 이미 해결하신거 같기도 해서요 !

https://github.com/spoqa/settei/blob/a7ec65f727065c5e035aa1abc523cfbdf7248c61/settei/presets/flask.py#L51-L60 web_config 가 typing.Mapping 이고, 따로 on_loaded는 넣어주고 있지 않아서 https://github.com/spoqa/settei/blob/a7ec65f727065c5e035aa1abc523cfbdf7248c61/settei/presets/flask.py#L119 요기서 web_config로 on_loaded를 가져올 수 없습니다!

web_config도 EnvReader를 상속 받도록 변경하면 될까요?! 🤔 

@kanghyojun  https://github.com/spoqa/settei/pull/40#discussion_r455527717 이 리뷰 빼고 전부 반영했습니다!

2020-07-23 06:45 UTC, kimdoori commented
생각해보니 worker_config와 web_config를 env에서 가져올 수 있도록 하는 게 원래 이 PR의 목표였네요.. 😅

2020-09-23 01:44 UTC, kanghyojun commented on tests/parse_env_test.py
> +        assert d['a']['c'] == '2'
둘다 잘 출력되어야합니다!

2020-09-23 01:44 UTC, kanghyojun commented on settei/base.py
> -        self.config = dict(config, **kwargs)
아마 저희 코드도 그렇지만 settei 사용 코드중에 `config`를 직접 사용하는 경우가 있을거 같아요. 해서 `config` 자체는 유지시키되 사용하지 말라는 경고정도를 띄워주는게 어떨까요?

```
@property
def config(self) -> Configuration:
    warnings.warn("settei.base.Configuration.config will be deleted, after <특정버전>", DeprecationWarning)
    return self
````

2020-09-28 07:18 UTC, kimdoori commented on settei/base.py
> -        self.config = dict(config, **kwargs)
좋습니다!!

2020-09-28 07:18 UTC, kimdoori commented on tests/parse_env_test.py
> +        assert d['a']['c'] == '2'
ㅠㅠ 안되네요ㅠ 좀 더 봐볼게요

2020-10-26 02:18 UTC, kimdoori commented on tests/parse_env_test.py
> +        assert d['a']['c'] == '2'
@kanghyojun 이거 구두로 여쭤봤을 때는 이런 상황도 지원해야한다고 말씀해주셨던 것 같은데 맞나요? 

```toml
[database]
pool_pre_ping = true
[database.connect_args]
options = "-c timezone=Asia/Seoul"
```

```python
'database': {
    'pool_pre_ping': True,
    'connect_args': {
        'options': '-c timezone=Asia/Seoul',
    }
}
```

> 혹시 A__C와 A가 둘다 있을때 d['a']와 d['a']['c'] 전부 잘 출력되는 테스트 추가해주실수 있을까요?

그러면 `A__B`와 `A__C__D` 가 둘다 있을 때 d['a']['b']와 d['a']['c']['d'] 로 테스트하면 되는 거 아닌가요?!

그 때 구두로 말씀해주셨을 때는 이해가 된 것 같은데 코드 짜면서 계속 생각해보니까 코멘트로 달아주신 상황에서는 덮어쓰기가 되는 게 맞는 것 같다는 생각이 들어서요! 아니라면 저를 한 번 더 이해시켜주시면 감사하겠습니다.. 🙏

2020-10-26 02:43 UTC, kimdoori commented
> > > on_loaded 함수에서 worker_config 나 web_config를 사용하도록 하고 싶은데 혹시 좋은 방법을 아시나요?
> > 
> > 
> > @kimdoori 혹시 이거 조금 더 자세하게 설명 들을 수 있을까요? 왠지 이미 해결하신거 같기도 해서요 !
> 
> https://github.com/spoqa/settei/blob/a7ec65f727065c5e035aa1abc523cfbdf7248c61/settei/presets/flask.py#L51-L60
> 
> web_config 가 ImmutableDict 이고, 따로 on_loaded는 넣어주고 있지 않아서
> https://github.com/spoqa/settei/blob/a7ec65f727065c5e035aa1abc523cfbdf7248c61/settei/presets/flask.py#L119
> 
> 요기서 web_config로 on_loaded를 가져올 수 없습니다!
> web_config도 EnvReader로 변경하면 될까요?! 🤔
> 
> @kanghyojun [#40 (comment)](https://github.com/spoqa/settei/pull/40#discussion_r455527717) 이 리뷰 빼고 전부 반영했습니다!

ㅎ.. 이 부분은 오래전이라 기억이 잘 나지 않지만.. on_loaded 불러오는 부분을 아래처럼 변경해서 해결된 것 같습니다!

```
on_loaded = self.get('web').get('on_loaded', [])
```

2020-10-26 02:43 UTC, kimdoori commented on tests/parse_env_test.py
> +        assert d['a']['c'] == '2'
👞 덮어쓰기 되는 게 맞습니다.

2020-10-26 04:21 UTC, kimdoori commented
@kanghyojun 리뷰 반영 전부 완료했습니다!! 확인 부탁드려요! changelog에 릴리즈 날짜는 오늘로 고쳐두긴 했는데 이렇게 하고 리뷰 완료 후에 머지하면 끝인가요? 배포는 어떻게 하나요?!

추가로 변경된 점은 아래와 같습니다.
- 리베이스 및 config 유지 리뷰 반영했습니다! [변경점](https://github.com/spoqa/settei/compare/e198776fcec9b7038d282a73d1aedc5db6f2b118..cbf34e55bf29c78d6f1e2855e9b26ede9c2142c5)
- list와 tuple도 config에 지정한 순서대로 정렬해서 반환하도록 수정했습니다. [변경점](https://github.com/spoqa/settei/compare/0720043300e8b5b4b6b56e8637d5f695633c81ea..15248b14ae9689dee63eea29925925d3953442d7
)
- 린트가 깨져서 수정했습니다. [변경점1](https://github.com/spoqa/settei/compare/b039252a30b57e072da1fa46387840984652e000..ad8ca8ad9d8b24a01073f0b0497f112364e5c12f) [변경점2](https://github.com/spoqa/settei/compare/ad8ca8ad9d8b24a01073f0b0497f112364e5c12f..2aeeeb4a03f59fa8de217cedbb13d33ab5d66b3a)
- changelog를 업데이트했습니다. [변경점](https://github.com/spoqa/settei/pull/40/commits/2aeeeb4a03f59fa8de217cedbb13d33ab5d66b3a)

@AiOO 이제 리뷰 부탁드립니다! 정말 오래 걸렸네요.. ㅎㅎ

2020-10-26 04:35 UTC, kanghyojun approved these changes

2020-10-26 04:35 UTC, kanghyojun commented on settei/base.py
> +            'settei.base.Configuration.config is deprecated.'
It will be removed after 0.8.0. 정도 써두는게 어때요?

2020-10-26 04:37 UTC, kimdoori commented
@kanghyojun https://github.com/spoqa/settei/compare/2aeeeb4a03f59fa8de217cedbb13d33ab5d66b3a..5639487c54ed010d7ac69c69c997670bfb6404c6 리뷰 감사해요! 반영했습니다!

2020-10-26 04:43 UTC, kimdoori commented
@kanghyojun https://github.com/spoqa/settei/compare/5639487c54ed010d7ac69c69c997670bfb6404c6..3a24b1cb53a562ef922f9599961c23c5a7e7cd38 마지막이길 바라며 멘션 드립니다 ㅎㅎㅎ

2020-10-26 04:46 UTC, kimdoori commented
@kanghyojun [포푸](https://github.com/spoqa/settei/compare/5639487c54ed010d7ac69c69c997670bfb6404c6..3a24b1cb53a562ef922f9599961c23c5a7e7cd38) 봐주시면 됩니다! 리뷰 봐주셔서 감사해요 🙇

2020-10-26 04:56 UTC, kanghyojun approved these changes

2020-10-26 05:43 UTC, AiOO commented
맥락이 기억나지 않아서 첨부터 다시 보겠습니다 ㅋㅋㅋㅋ

2020-10-26 08:08 UTC, AiOO approved these changes
오래된 이슈 해결해주시느라 고생 많으셨습니다. 기여해주셔서 감사해요! 🎉

2020-10-26 10:21 UTC, merged